# Generated by Django 2.0.4 on 2018-06-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlfinstatisticasof',
            name='nav',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hlfinstatisticasof',
            name='p_nav',
            field=models.FloatField(default=0),
        ),
    ]
