# Generated by Django 2.0.4 on 2018-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetdata', '0002_auto_20180616_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='bookvaluepershare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='dvdyield',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='lastprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='marketcap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='p_bv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hlfinstatisticasof',
            name='p_e',
            field=models.FloatField(default=0),
        ),
    ]
