# Generated by Django 2.1 on 2018-07-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsetdata', '0004_auto_20180627_2236'),
        ('getsetdata', '0004_auto_20180618_1306'),
    ]

    operations = [
    ]
