# Generated by Django 2.0.4 on 2018-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitorbidoffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastershare', models.CharField(default='', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid1', models.FloatField()),
                ('offer1', models.FloatField()),
                ('bidvolumn1', models.FloatField()),
                ('offervolumn1', models.FloatField()),
                ('bid2', models.FloatField()),
                ('offer2', models.FloatField()),
                ('bidvolumn2', models.FloatField()),
                ('offervolumn2', models.FloatField()),
                ('bid3', models.FloatField()),
                ('offer3', models.FloatField()),
                ('bidvolumn3', models.FloatField()),
                ('offervolumn3', models.FloatField()),
                ('bid4', models.FloatField()),
                ('offer4', models.FloatField()),
                ('bidvolumn4', models.FloatField()),
                ('offervolumn4', models.FloatField()),
                ('bid5', models.FloatField()),
                ('offer5', models.FloatField()),
                ('bidvolumn5', models.FloatField()),
                ('offervolumn5', models.FloatField()),
            ],
        ),
    ]
