# Generated by Django 2.0.4 on 2019-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterefresh',
            name='matchedtime',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
