# Generated by Django 2.1 on 2019-02-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='udpatestockvalue',
        ),
        migrations.AddField(
            model_name='valuechange',
            name='orderstate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
