# Generated by Django 2.1 on 2018-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valuechange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefield', models.DateTimeField(verbose_name=0)),
                ('timestamp', models.DateTimeField(verbose_name=0)),
                ('stockname', models.CharField(max_length=5)),
                ('valuefield', models.CharField(default='', max_length=5)),
                ('totalvolume', models.CharField(default='', max_length=15)),
                ('totalvolue', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
