# Generated by Django 2.1 on 2018-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorbidoffer',
            name='mastershare',
            field=models.CharField(default='', max_length=50),
        ),
    ]
