# Generated by Django 2.1 on 2018-10-30 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0002_updaterefresh_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterefresh',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 17, 40, 47, 747236)),
        ),
    ]
