# Generated by Django 2.1 on 2018-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0002_auto_20180704_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorbidoffer',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
