# Generated by Django 2.1 on 2018-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0002_valuechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuechange',
            name='datefield',
            field=models.DateField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='valuechange',
            name='timestamp',
            field=models.TimeField(verbose_name=0),
        ),
    ]
