# Generated by Django 2.0.4 on 2018-11-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0003_auto_20181114_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuechange',
            old_name='valuefield',
            new_name='stockvalue',
        ),
    ]
