# Generated by Django 2.1 on 2019-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0003_keepconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepconfig',
            name='source',
            field=models.CharField(default='', max_length=15),
        ),
    ]
