# Generated by Django 2.1 on 2018-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0003_auto_20181030_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterefresh',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
