# Generated by Django 2.0.4 on 2019-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0003_auto_20190217_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterefresh',
            name='referorderno',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
