# Generated by Django 2.1 on 2018-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0003_auto_20180704_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorbidoffer',
            name='timestamp',
            field=models.DateTimeField(verbose_name=0),
        ),
    ]
