# Generated by Django 2.0.4 on 2019-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0004_keepconfig_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepconfig',
            name='planvalue',
            field=models.CharField(default='', max_length=3),
        ),
    ]
