# Generated by Django 2.1 on 2018-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0004_auto_20180705_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='udpatestockvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuefield', models.CharField(default='', max_length=10)),
                ('datefield', models.DateTimeField(verbose_name=0)),
                ('timefield', models.DateTimeField(verbose_name=0)),
                ('orderfield', models.CharField(default='', max_length=5)),
                ('statusfield', models.CharField(default='', max_length=5)),
                ('volumnfield', models.CharField(default='', max_length=10)),
                ('buyfield', models.CharField(default='', max_length=5)),
                ('sellfield', models.CharField(default='', max_length=5)),
                ('cancelfield', models.CharField(default='', max_length=5)),
                ('targetvalue', models.CharField(default='', max_length=10)),
                ('profitfield', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
