# Generated by Django 2.0.4 on 2018-10-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0005_udpatestockvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='updaterefresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(default='', max_length=10)),
                ('symbole', models.CharField(default='', max_length=10)),
                ('time', models.CharField(default='', max_length=10)),
                ('side', models.CharField(default='', max_length=3)),
                ('price', models.CharField(default='', max_length=10)),
                ('volume', models.CharField(default='', max_length=10)),
                ('matched', models.CharField(default='', max_length=10)),
                ('balance', models.CharField(default='', max_length=10)),
                ('cancelled', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
