# Generated by Django 2.0.4 on 2018-11-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0005_auto_20181115_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuechange',
            name='stockname',
            field=models.CharField(max_length=10),
        ),
    ]
