# Generated by Django 2.1 on 2019-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0006_auto_20190327_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepconfig',
            name='planname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
