# Generated by Django 2.1 on 2019-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0006_auto_20181125_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterefresh',
            name='matchedtime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='updaterefresh',
            name='referorderfrom',
            field=models.CharField(default='', max_length=10),
        ),
    ]
