# Generated by Django 2.1 on 2019-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0007_keepconfig_planname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keepconfig',
            old_name='planvalue',
            new_name='planselect',
        ),
    ]
