# Generated by Django 2.1 on 2019-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0009_auto_20190401_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepconfig',
            name='planselect',
            field=models.CharField(default='', max_length=5),
        ),
    ]
