# Generated by Django 2.1 on 2019-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0010_auto_20190401_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keepconfig',
            name='stockname',
        ),
        migrations.AddField(
            model_name='keepconfig',
            name='monitorstock',
            field=models.CharField(default='', max_length=10),
        ),
    ]
