# Generated by Django 2.0.4 on 2019-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0013_auto_20190628_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='keeplogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokeId', models.CharField(max_length=3)),
                ('loginId', models.CharField(default='', max_length=10, unique=True)),
                ('passwordId', models.CharField(default='', max_length=15, unique=True)),
                ('pinId', models.CharField(max_length=10)),
            ],
        ),
    ]
