# Generated by Django 2.0.4 on 2019-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0014_keeplogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeplogin',
            name='brokeId',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='keeplogin',
            name='loginId',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='keeplogin',
            name='passwordId',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='keeplogin',
            name='pinId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
