# Generated by Django 2.0.4 on 2019-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0016_auto_20190704_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeplogin',
            name='currentuseId',
            field=models.CharField(default='', max_length=5),
        ),
    ]
