# Generated by Django 2.0.4 on 2019-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0018_auto_20190708_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeplogin',
            name='brokeId',
            field=models.CharField(max_length=3),
        ),
    ]
