# Generated by Django 2.0.4 on 2019-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0019_auto_20190709_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keepconfig',
            old_name='planselect',
            new_name='rangeselect',
        ),
        migrations.AddField(
            model_name='keepconfig',
            name='currentuseId',
            field=models.CharField(default='', max_length=5),
        ),
    ]
