# Generated by Django 2.0.4 on 2019-07-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0020_auto_20190710_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keepconfig',
            old_name='stopvaluerange',
            new_name='stopvaluebuy',
        ),
    ]
