# Generated by Django 2.0.4 on 2019-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0021_auto_20190710_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepconfig',
            name='planname',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
