# Generated by Django 2.0.4 on 2019-07-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0022_auto_20190710_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keepconfig',
            old_name='floorvaluerange',
            new_name='floorvaluebuy',
        ),
        migrations.RenameField(
            model_name='keepconfig',
            old_name='topvaluerange',
            new_name='topvaluebuy',
        ),
    ]
