# Generated by Django 2.0.4 on 2019-07-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0023_auto_20190722_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepconfig',
            name='runningmode',
            field=models.CharField(default='auto', max_length=8),
        ),
    ]
