# Generated by Django 2.0.4 on 2019-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkybot', '0024_keepconfig_runningmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepconfig',
            name='remaininvest',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='keepconfig',
            name='totalvaluebuy',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='keepconfig',
            name='totalvolumebuy',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
